const fs = require('fs');
const { JSDOM } = require('jsdom');
const html = fs.readFileSync('D:/学习/体系文件/统一学习平台/index.html', 'utf8');
(async () => {
  const dom = new JSDOM(html, { runScripts: 'dangerously', resources: 'usable', url: 'file:///D:/学习/体系文件/统一学习平台/index.html', pretendToBeVisual: true });
  const w = dom.window, d = w.document;
  w.alert = () => {}; w.confirm = () => true; w.scrollTo = () => {};
  const $ = id => d.getElementById(id);
  const fire = (el, ev) => el.dispatchEvent(new w.Event(ev, { bubbles: true, cancelable: true }));
  await new Promise(r => setTimeout(r, 800));
  $('tabReg').click();
  $('rgUser').value = 'zhangsan';
  $('rgNick').value = '张三';
  $('rgPass').value = '1234';
  $('rgPass2').value = '1234';
  fire($('formReg'), 'submit');
  await new Promise(r => setTimeout(r, 200));
  console.log('portalUser text =', JSON.stringify($('portalUser').textContent));
  console.log('sessionStorage =', JSON.stringify(w.sessionStorage.getItem('unified_learn_session')));
  console.log('users stored   =', JSON.stringify(JSON.parse(w.localStorage.getItem('unified_learn_users_v1'))));
  d.querySelectorAll('.portal-card')[0].querySelector('.pc-btn').click();
  await new Promise(r => setTimeout(r, 3000));
  console.log('totalCount =', $('totalCount').textContent);
  $('lecToQuiz').click();
  await new Promise(r => setTimeout(r, 100));
  d.querySelector('#qOptions .opt').click();
  await new Promise(r => setTimeout(r, 100));
  console.log('sDone =', $('sDone').textContent);
  console.log('KEY stored =', Object.keys(w.localStorage).filter(k => k.indexOf('unified_v1') === 0));
  $('btnBackPortal').click();
  await new Promise(r => setTimeout(r, 100));
  console.log('portal card1 progress =', JSON.stringify(d.querySelectorAll('.portal-card')[0].querySelector('.pc-progress').textContent));
  process.exit(0);
})().catch(e => { console.error(e); process.exit(1); });
